### ISSUE TITLE
Transfer repository to rosin-project org?

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/haros_catkin#1]
@ipa-jfh: we're (@itualami, @nlimpert, @droter and I) trying to continue the work wrt haros and the ROS buildfarm.

In that context, would you be ok with transferring this repository to [rosin-project](https://github.com/rosin-project)?

**Comment by gavanderhoorn** [comment]
And the same for [haros_catkin_test](https://github.com/ipa-jfh/haros_catkin_test) of course.

**Comment by Chamango90** [comment]
Hi @gavanderhoorn my apologies for the late reply. Yes I would be ok with that.

**Comment by gavanderhoorn** [comment]
@ipa-jfh: could you initiate the migration then? It'd be easiest if you first migrate it to my personal account. Afterwards I'll migrate it to `rosin-project`.

**Comment by Chamango90** [comment]
Sorry for the late reply again. I tried to transfer it to you, however 

> gavanderhoorn/haros_catkin already exists

Could you delete/rename your fork?

**Comment by gavanderhoorn** [comment]
Done.

**Comment by Chamango90** [comment]
The renaming was not enough since it is a fork of my repo.

> gavanderhoorn already has a repository in the ipa-jfh/haros_catkin network

**Comment by gavanderhoorn** [comment]
Hm.

Just deleted my fork.

**Comment by gavanderhoorn** [comment]
Thanks for the transfer @ipa-jfh :+1: 

And thanks for the work on `haros_catkin`.
