### ISSUE TITLE
make report output location configurable

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/haros_catkin#5]
The `haros_report` macro should be extended to make the location to which the haros output will be written configurable using some argument.

Perhaps a `REPORT_DESTINATION` named argument.

**Comment by nlimpert** [comment]
We might be able to use `REPORT_DESTINATION` as an environment variable and evaluate it in `haros_catkin-extras.cmake.em` via `$ENV{REPORT_DESTINATION}`.

If it's not available we might stick with the setting as it is currently.

**Comment by gavanderhoorn** [comment]
Any reason not to go with a named argument to the macro? That's typically how CMake macros are provided with input data.

**Comment by nlimpert** [comment]
No - using `$ENV{}` was meant as an additional suggestion. But I agree that an argument is the better option.

**Comment by gavanderhoorn** [comment]
Using the environment could be an option, but for traceability it's less desirable I believe: the "environment" could contain "anything", and typical logs don't reflect what the state of `ENV` was at the time of a run.

Commands invoked can relatively easily be logged, including arguments, and in any case `CMakeLists.txt` containing the invocation would be stored in VCS, facilitating post-mortem debugging.

**Comment by nlimpert** [comment]
OK I agree. I didn't think of traceability concerns in the first place.
So nevermind.

**Comment by gavanderhoorn** [comment]
Picking this up again: `roslint` uses a variable called `CATKIN_TEST_RESULTS_DIR` ([here](https://github.com/ros/roslint/blob/6c963f3010c94d4b13123f468ce8ca4844ee20c4/cmake/roslint-extras.cmake.em#L73)). I'm wondering how that is supposed to work, as apparently that variable has been removed quite some time ago (`ros-sig-buildsystem` discussion [here](https://groups.google.com/forum/#!topic/ros-sig-buildsystem/suBvWzoGODU)).

Right now the haros report ends up in `${CMAKE_CURRENT_BINARY_DIR}/test_results/haros_report` (which resolves to `$CATKIN_WS/build/<pkg_name>/test_results/haros_report` for me). Other test results appear to end up in `$CATKIN_WS/test_results/` (I'm running things in a prerelease container, so perhaps this is specific to that environment).

I'm wondering whether there is some default location that we could use instead.

**Comment by nlimpert** [comment]
> I'm wondering whether there is some default location that we could use instead.

I'm not sure whether I remember the complete discussion about the actual desired location of reports to be used in the ROS Wiki but I think unless we decided how/where reports would reside to be rendered by the ROS Wiki we might stick with the `CMAKE_CURRENT_BINARY_DIR`.

**Comment by gavanderhoorn** [comment]
This can now be configured using the argument parsing added in #19.
