### ISSUE TITLE
Support specifying a custom haros configuration

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/haros_catkin#7]
The [current implementation](https://github.com/rosin-project/haros_catkin/blob/735a6c6316d9b72754085bc30739accad673354f/cmake/haros_catkin-extras.cmake.em#L17) of the `haros_report` macro takes no arguments, which makes it impossible to ask haros to use a specific configuration -- other than changing the "global" configuration stored in the `$HOME/.haros` repository.

It would be desirable to be able to specify a path to a configuration file/directory to be used for a specific run.

Perhaps a named argument (`CONFIG_PATH`?) should be added to the macro and then pass this location on to `haros` itself.

**Comment by nlimpert** [comment]
I think https://github.com/git-afsantos/haros/pull/74 would be required to allow this (hence the PR).

**Comment by gavanderhoorn** [comment]
Supported now in Haros and in `haros_catkin` (with the merge of #19).
