### ISSUE TITLE
Order of statements in build script

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/haros_catkin#9]
@ipa-jfh: I seem to remember there was a good reason for this, but I don't remember what it was and I can't find it in comments or the history of this repository, so I'm hoping I can ask you.

Thing is: according to the [readme](https://github.com/locusrobotics/catkin_virtualenv/blob/836c3f71086209d3359e2352c95960e22eb95408/README.md) of `catkin_virtualenv`, there is a certain order to the statements to make it work (from the [*Bundling virtualenv* section](https://github.com/locusrobotics/catkin_virtualenv/blob/836c3f71086209d3359e2352c95960e22eb95408/README.md#bundling-virtualenv)):

```cmake
find_package(catkin REQUIRED ... catkin_virtualenv ...)
catkin_package()
catkin_generate_virtualenv()
```

The `CMakeLists.txt` for `haros_catkin` has this order ([here](https://github.com/rosin-project/haros_catkin/blob/735a6c6316d9b72754085bc30739accad673354f/CMakeLists.txt)):

```cmake
find_package(catkin REQUIRED COMPONENTS catkin_virtualenv)
catkin_destinations()
catkin_generate_virtualenv()
catkin_package(
  CFG_EXTRAS ${PROJECT_NAME}-extras.cmake
  EXPORTED_TARGETS ${PROJECT_NAME}_generate_virtualenv
)
```

That goes against what the `readme` suggests.

Re-ordering statements to 'fix' the order results in a failing build:

```
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:372 (message):
  catkin_package() could not find target 'haros_catkin_generate_virtualenv'
  for code generation.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:8 (catkin_package)
```

So it seems this order is needed for this to work with `haros_catkin`.

Would you happen to remember why you did this?

**Comment by Chamango90** [comment]
Unfortunately, I cannot remember a specific reason  :/

**Comment by gavanderhoorn** [comment]
Hm, that's unfortunate.

I think I understand why `catkin_destinations()` is called before `catkin_generate_virtualenv()`: the latter uses the variables `set(..)` by the former.

I'm having all sorts of trouble getting the build to succeed in a `ros_buildfarm` prerelease job, so was wondering whether this could be (partly) the cause.

**Comment by Chamango90** [comment]
> The CMakeLists.txt for haros_catkin has this order (here):
> 
> find_package(catkin REQUIRED COMPONENTS catkin_virtualenv)
> catkin_destinations()
> catkin_generate_virtualenv()
> catkin_package(
>   CFG_EXTRAS ${PROJECT_NAME}-extras.cmake
>   EXPORTED_TARGETS ${PROJECT_NAME}_generate_virtualenv
> )

I asked also ipa-mdl, since we worked together on this. He says that it this order is necessary  because `catkin_generate_virtualenv` requires the destinations.

(The readme might be sloppy.)

**Comment by gavanderhoorn** [comment]
Yes, that's what I wrote in my comment before yours :)

but thanks for the additional input.

**Comment by Chamango90** [comment]
Sry I missed to include your latest comment. He added that the pkg depends on the target from `catkin_generate_virtualenv()`.

> EXPORTED_TARGETS ${PROJECT_NAME}_generate_virtualenv

**Comment by gavanderhoorn** [comment]
We haven't cleared up everything, but good enough for now.

Thanks @ipa-jfh for the input.
